spring:
  profiles:
    active: system-datasource
  application:
    name: WebfluxApp
  cache:
    type: redis
  redis:
    host: 192.168.0.111
    port: 6379
    database: 0
    client-type: lettuce
    client-name: ${spring.application.name}-Cache
    timeout: PT3S
    connect-timeout: PT3S
    lettuce:
      pool:
        max-wait: 3000
        max-idle: 8 #电脑核数乘以 2
        max-active: 8 #电脑核数乘以 2
        min-idle: 1
        time-between-eviction-runs: PT1M
jwt:
  secretKey: abcdefghijklmnopqrstuvwxyz0123456789
  validityInMills: 1_800_000
