db:
  name: webflux-angular
spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:mysql://localhost:3306/${db.name}?serverZoneId=Asia/Shanghai&tcpKeepAlive=true&tcpNoDelay=true
    pool:
      initial-size: 2
  flyway:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Shanghai
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    default-schema: ${db.name}
