spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:mysql://localhost:3306/ds1?serverZoneId=Asia/Shanghai&tcpKeepAlive=true&tcpNoDelay=true
    pool:
      initial-size: 2
  flyway:
    url: jdbc:mysql://localhost:3306/ds1?serverTimezone=Asia/Shanghai
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
